# -*- coding: utf-8 -*-
"""05.04.01 Exercícios if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjcqciIJtjIfCFgoiGJIHEAwsVXTME1Z

# Exercícios com if

## 1. Cálculo de Bônus

- Crie um programa que calcule e dê um print no bônus que os funcionários devem receber segundo a regra:

A meta é 1000 vendas.<br> 
Se o valor de vendas for maior ou igual a meta, o valor do bônus do funcionário é 10% do valor de vendas.<br>
Caso contrário o valor de bônus do funcionário é 0.<br>
Print o bônus dos 3 funcionários
"""

vendas_funcionario1 = 1000
vendas_funcionario2 = 770
vendas_funcionario3 = 2700

meta_vendas = 1000

if vendas_funcionario1 >= meta_vendas:
    bonus = 0.10 * vendas_funcionario1
    print(f'Sua bonificação foi de {bonus}, parabéns!!')
else:
    print('Você não teve bonificação!!')


if vendas_funcionario2 >= meta_vendas:
    bonus = 0.10 * vendas_funcionario2
    print(f'Sua bonificação foi de {bonus}, parabéns!!')
else:
    print('Você não teve bonificação!!')


if vendas_funcionario3 >= meta_vendas:
    bonus = 0.10 * vendas_funcionario3
    print(f'Sua bonificação foi de {bonus}, parabéns!!')
else:
    print('Você não teve bonificação!!')
